/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class org_liuyehcf_jni_JniDemo */

#ifndef _Included_org_liuyehcf_jni_JniDemo
#define _Included_org_liuyehcf_jni_JniDemo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_liuyehcf_jni_JniDemo
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_liuyehcf_jni_JniDemo_sayHello
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
