DROP DATABASE mybatis;
CREATE DATABASE mybatis;

USE mybatis;

CREATE TABLE user(
id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
name VARCHAR(20) NOT NULL,
age INT UNSIGNED NOT NULL,
PRIMARY KEY(id),
UNIQUE KEY(name)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;